### ISSUE TITLE
[VOTE] code-styling/markdown: Max line length

### ISSUE THREAD

**Issue by frenck** [DealerDirect/guides#2]
This vote is about the [Markdown code styling guide](https://github.com/DealerDirect/guides/blob/master/code-styling/markdown/README.md).

The PR for the initial version of the guide caused some discussion about the max line length to go for. The original suggested max line length by me was 120 characters, some agreed, others would like to see a max line length of 80.

For the full and original discussion, please see PR #1.

Question voting yay/nay for:

**Keep the current max line length of 120 characters?**

Can I get a vote yay/nay for all of those eligible to vote?

## Eligable to vote

| Developer | Yay | Nay |
| --- | --- | --- |
| @arjank | | ☑️ |
| @brammittendorff-dd | ☑️ | |
| @Dravenshorst | | ☑️ |
| @eaulav | ☑️ | |
| @edvance | | ☑️ |
| @frenck | ☑️ | |
| @Marascon | | ☑️ |
| @mjbakker | | ☑️ |
| @pimkaptein | ☑️ | |
| @potherca | | ☑️ |
| @Terrub | | ☑️ |
| @wouteroostervld | | |
| Total = 11 | 4 | 7 |

Please explain the reason for your nay/yay vote in a comment.

## Not eligable to vote

| Developer | Yay | Nay |
| --- | --- | --- |
| @hipio  | ☑️  | |

**Comment by brammittendorff-dd** [comment]
Yay

**Comment by ghost** [comment]
Yay, I highly prefer 120 characters over 80 for the reason stated by @frenck.

**Comment by frenck** [comment]
Yay.

We live in a modern world, with wide screens.
The 80 character limit original existed because of terminal screens. Since we don't live in this world anymore, the 120 character limit becomes more and more the standard.

**Comment by Potherca** [comment]
The statement by @frenck isn't entirely correct, that is to say, it's even worse than that. 
The common coding standard is a result of the IBM's 1928 80 column punched card format.

![IBM Punchcard](http://i.stack.imgur.com/XvPKy.jpg)

<sup>source: http://softwareengineering.stackexchange.com/questions/148677</sup>

There are, however, other reasons beside punchcards, terminals and screen size that come into play. 

> It turns out that the subconscious mind is energized when jumping to the next line (as long as it doesn’t happen too frequently, see above bullet point). At the beginning of every new line the reader is focused, but this focus gradually wears off over the duration of the line (“Typographie”, E. Ruder).
> 
> In order to avoid the drawbacks of too long and too short lines, but still energize your readers and keep them engaged, we suggest keeping your text within the range of 50-75 characters per line.
> 

<sup>source: http://baymard.com/blog/line-length-readability</sup>

Besides this, code is not just displayed in the Editor, it is displayed in Diff-tools, (browser based) code review tools, emails, bug trackers, etc. People with laptops with small screens will work on the same code-base as user with "broad" screens.

Wider lines means more scrolling in a lot of such tools as "line-wrap" is not universally implemented.

When stating "120 works for me", effectively you are not taking other scenario's into account than your current working scenario. It is basically a poorly disguised 
![cheap cop out](http://www.edsquared.com/content/binary/Windows-Live-Writer/dbb6c39a79dc_68DE/WorksOnMyMachine_3.png)

There is a difference between code, markup and generated output. For code the 80-ish (50-75 characters + indentation whitespace) is more important than for markup, as code is more frequently read and updated than docs.

**However**, as this decision is likely to cascade down into other standards "we" (as a company) use, I am not in favour of stretching the line length beyond 80 characters.

**Comment by frenck** [comment]
Wauw @Potherca nice history lesson! 👍 
I guess it all comes down to personal preferences like chrome vs firefox, where even all the pros/cons don't even make sense anymore.

Same goes for hard vs soft limit. Some specs even suggest 2 soft limits (like PHP's PSR-2), which is even more insane. I personally prefer one single hard limit. Easy to understand and checkable using automated checks. Having a soft limit is like saying: "Nah well ok, we have a rule or something, but you can ignore it". (PSR-2: "We have 2 conflicting rules, but hey! You can ignore both")

My personal preference is a hard 120 character limit, since I feel like 80 is sometimes to small and can be quite annoying while coding (especially when indented a couple of levels). Yeah i know... this guide is about documentation... but it is not about the documentation itself!

This guide is about the Markdown code, not about reading it. Reading would be rendered by the browser (or other viewing tool), which takes care of the "width" of lines displayed and has absolutely nothing to do with how it is shown in the actual code.

So that actually leaves some diff tools (like the one from ButtBucket) and coding / side by side diffing on laptop screens. Is it worth going for 80 characters? I personally do not think so.

Nevertheless, nice write up and an interesting point of view! It even made me doubt my initial choice for a while.

**Comment by Terrub** [comment]
First of all: I think it ludicrous to spend time on such a "high risk, low reward"-kind of issue. Especially this amount of time. However, since I'm part of the minority here, I suppose I should let my voice be heard.

I don't exactly know the reasons why 80 is a standard, nor do I know for sure that it is even a standard.
I don't know enough about what systems we use that can or perhaps do, rely on that 80 limit. I don't know if those systems use systems that rely on that limit.
I do not know how deep these roots go. All I see is that this potentially goes back to the days of punch cards. That's a **lot** of human history and human made progress and change. That also means a **lot** of human error.

I personally care very little for having to dig through that amount of information just to say whether it's safe to make the change to 120.
And frankly, I don't think releaving occasional annoyance is enough of a reason to keep people from reverting back to 80 as soon as that history digs up a big snag.

I'm not saying be afraid of the unknown and do nothing but the safe and the well known. I'm saying have a good reason to keep you motivated when you go on such an adventure because adventures are awesome and cool but also draining and filled with hard times and require hard work. Thus far I'm not seeing any good reasons for going on this adventure of the 120 char limit.

So can we instead focus on the adventures that we _are_ motivated for?

**Comment by arjank** [comment]
As previously indicated, I prefer a soft limit of 80 characters and a hard limit of 120 characters.

**Comment by Potherca** [comment]
I would also prefer a "SHOULD be less than 80 MUST be less than 120" version.

**Comment by edvance** [comment]
Agree, like that version too.

**Comment by Marascon** [comment]
Would like a soft and hard limit even better.

**Comment by mjbakker** [comment]
Less is more. So I would say Nay

**Comment by frenck** [comment]
This morning during the standup we've voted for the following option:

"SHOULD be less than 80 MUST be less than 120 characters"

This means a soft limit of 80 and a hard limit of 120 characters.

Vote results: Overwhelmingly yay, only 2 nay.

Guide will be updated to reflect this vote.
